from enum import Enum

class Skills(Enum):
    PYTHON = "Python"
    JAVA = "Java"
    JAVASCRIPT = "JavaScript"
    CSHARP = "C#"
    RUBY = "Ruby"
    GO = "Go"
    SWIFT = "Swift"
    KOTLIN = "Kotlin"
    PHP = "PHP"
    TYPESCRIPT = "TypeScript"
    SQL = "SQL"
    HTML = "HTML"
    CSS = "CSS"
    RUST = "Rust"
    SCALA = "Scala"
    PERL = "Perl"
    HASKELL = "Haskell"
    LUA = "Lua"
    DART = "Dart"
    ELIXIR = "Elixir"
    CPLUSPLUS = "C++"
    C = "C"
    FPGA = "FPGA"
    ASSEMBLY = "Assembly"
    MATLAB = "MATLAB"
    R = "R"
    OOP = "Object-Oriented Programming"
    FUNCTIONAL = "Functional Programming"
